Adicionando o kill -9
lucascbittencourt/linux4noobs pull request #10
Opened 2020-03-10 22:22 UTC by marcopandolfo

2020-03-10 23:14 UTC, lucascbittencourt requested changes

2020-03-10 23:14 UTC, LucasHe4rt commented on 2-Linha De Comando/2-Comandos.md
> +Assim **forçamos** a parada do prograva de id *13421*
Precisa substituir a palavra **prograva** por **programa**

2020-03-10 23:15 UTC, lucascbittencourt approved these changes

2020-03-10 23:18 UTC, lucascbittencourt approved these changes

2020-03-13 02:20 UTC, franciscofpll approved these changes

2020-03-13 02:20 UTC, merged